name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent runaway costs
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write  # Required for OIDC
      actions: read # Required for Claude to read CI results on PRs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::119175775298:role/pmm-claude-bedrock-github-actions
          aws-region: us-east-2
          role-session-name: ClaudeBot-${{ github.run_id }}

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          # Configure for AWS Bedrock
          claude_args: '--model us.anthropic.claude-opus-4-1-20250805-v1:0 --max-tokens 16000'
        env:
          CLAUDE_CODE_USE_BEDROCK: "true"
          AWS_REGION: us-east-2
          AWS_DEFAULT_REGION: us-east-2
          ANTHROPIC_MODEL: "us.anthropic.claude-opus-4-1-20250805-v1:0"
          ANTHROPIC_SMALL_FAST_MODEL: "us.anthropic.claude-3-5-haiku-20241022-v1:0"

