name: Test OIDC Authentication

on:
  workflow_dispatch:
  push:
    branches: [main, feature/setup-oidc-workflow]
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::119175775298:role/pmm-claude-bedrock-github-actions
          aws-region: us-east-2
          role-session-name: GitHubActions-${{ github.run_id }}
      
      - name: Test AWS access
        run: |
          echo "Testing AWS access via OIDC..."
          aws sts get-caller-identity
          echo "Successfully authenticated via OIDC!"
      
      - name: List available Bedrock models
        run: |
          echo "Listing available Bedrock models..."
          aws bedrock list-foundation-models --region us-east-2 --query "modelSummaries[?contains(modelId, 'claude')].{ModelId:modelId, ModelName:modelName}" --output table || true
      
      - name: Test Bedrock access
        run: |
          echo "Testing Bedrock access..."
          aws bedrock list-inference-profiles --region us-east-2 --max-results 10 || true